### ISSUE TITLE
学习范围补充

### ISSUE THREAD

**Issue by IcyDesert** [HITSZ-OpenAuto/EE1013#1]
据机器人与智能装备电路授课老师和军平所述，机器人专业《电路理论基础》仅上第一至四章，且目前涉及运放的内容均不讲。而有消息说本课程是三个集群统一内容，因此其他专业也可能是这种形式。

**Comment by OliverWu515** [comment]
是啊，我不是这样写的吗？

**Comment by OliverWu515** [comment]
我说的预习参考，包含了我认为所有初学者应该接触的范围，是针对对自己要求较高的同学的。我可以补充一下。

**Comment by IcyDesert** [comment]
嗯，确实我看漏了；但是运放部分，据一位自动化的同学所述，不在电路里讲，放在模电/数电部分讲。

**Comment by OliverWu515** [comment]
> 嗯，确实我看漏了；但是运放部分，据一位自动化的同学所述，不在电路里讲，放在模电/数电部分讲。

是的。我可以标出来。
