### ISSUE TITLE
《教学日历》无对应文件夹

### ISSUE THREAD

**Issue by IcyDesert** [HITSZ-OpenAuto/EE1013#3]
模电老师已发布《教学日历》，其中包含授课范围，可以作为**课程大纲**类文件；但是现有文件夹 assignments  exams  labs  notes  slides 似乎都不太对应这个文件。
目前有几个想法： 
1.  上传至 slides 文件夹，因为它确实是「课件、讲义、教师提供的参考资料」；但，又和课程具体知识关系不大。
2.  新建一个文件夹、传入其中，暂定名字为  schedules 。
3.  直接将其中内容写进 README.md，但考虑到每一届学习范围可能变化，不够灵活。

应该采取哪个措施呢？或者有更好的解决办法？

**Comment by kowyo** [comment]
可以考虑像 [自动控制实践](https://hoa.moe/docs/junior-autumn/auto3002a/) 的学时安排表一样整合到课程文档，因为这也是课程的重要信息。

**Comment by IcyDesert** [comment]
> 可以考虑像 [自动控制实践](https://hoa.moe/docs/junior-autumn/auto3002a/) 的学时安排表一样整合到课程文档，因为这也是课程的重要信息。

那大概需要等课程完结才能整理出来了

**Comment by OliverWu515** [comment]
> > 可以考虑像 [自动控制实践](https://hoa.moe/docs/junior-autumn/auto3002a/) 的学时安排表一样整合到课程文档，因为这也是课程的重要信息。
> 
> 那大概需要等课程完结才能整理出来了

该整了（doge）

**Comment by IcyDesert** [comment]
> > > 可以考虑像 [自动控制实践](https://hoa.moe/docs/junior-autumn/auto3002a/) 的学时安排表一样整合到课程文档，因为这也是课程的重要信息。
> > 
> > 
> > 那大概需要等课程完结才能整理出来了
> 
> 该整了（doge）

小登竟然还有三合一吗 Σ(⊙▽⊙"a

**Comment by WDGaster703** [comment]
> > > 可以考虑像 [自动控制实践](https://hoa.moe/docs/junior-autumn/auto3002a/) 的学时安排表一样整合到课程文档，因为这也是课程的重要信息。
> > 
> > 
> > 那大概需要等课程完结才能整理出来了
> 
> 该整了（doge）

已完成（doge）
